name: latatrack
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  app_color: ^1.0.7
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

fonts:
  - family: Roboto
    fonts:
      - asset: assets/font/Roboto-Regular.ttf
      - asset: assets/font/Roboto-Medium.ttf
        weigth: 500
      - asset: assets/font/Roboto-Light.ttf
        weigth: 600
      - asset: assets/font/Roboto-Bold.ttf
        weigth: 700
